//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long Id { get; set; }
        public string Location_Name { get; set; }
        public string Devices_IN_ { get; set; }
        public string Devices_OUT { get; set; }
        public string User_Notification { get; set; }
    }
}
