//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UID { get; set; }
        public string First_Name_ { get; set; }
        public string Last_Name_ { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Photo { get; set; }
        public Nullable<System.Guid> Thumbnail { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string Rights { get; set; }
        public string Card_ID { get; set; }
    }
}
