//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioData
{
    using System;
    using System.Collections.Generic;

  public enum VisitorStatus
  {
      VerificationSuccess
    , VerificationFailed
  }
    
    public partial class Visitor
    {
        public long UID { get; set; }
        public Nullable<long> User_UID { get; set; }
        public Nullable<long> Photo_ID { get; set; }
        public Nullable<long> Full_Photo_ID { get; set; }
        public byte[] Detection_Time { get; set; }
        public Nullable<long> Locaion_ID { get; set; }
        public string Status { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
